version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3309:3306"
    networks:
      - elMigrant

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8010:80
    environment:
      PMA_HOST: db
    networks:
      - elMigrant

  www:
    build: docker/php
    container_name: el_migrant
    ports:
      - "8002:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/html
    restart: always
    networks:
      - elMigrant

networks:
  elMigrant:

volumes:
  db-data: